name: CI

on:

  push:
    branches: [ "origin/main" ]
  pull_request:
    branches: [ "origin/main" ]

  workflow_dispatch:
jobs:
  BuildKernel:
    runs-on: ubuntu-22.04
    environment: TOKEN
    env:
      TOKEN: ${{ secrets.TOKEN_ID }}
    steps:
      - uses: actions/checkout@v4        
      - name: build kernel
        run: |
          rm -rf KernelSU-Next
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -
          sudo apt update
          sudo apt install android-tools-mkbootimg bc bison build-essential ca-certificates cpio curl flex git kmod libssl-dev libtinfo5 python2 sudo unzip wget xz-utils -y --no-install-recommends
          sudo ln -sf python2.7 /usr/bin/python
          sudo -S TOKEN=$TOKEN ./tg.sh

      - name: upload kernel
        uses: actions/upload-artifact@master
        with:
            name: EXTRACKME
            path: Quartz*.zip
